site_name: My Docs
theme:
  name: material
plugins:
- gen-files:
    scripts:
      - gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
    implicit_index: false
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google