[tool.poetry]
name = "quantfreedom"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.10"
dash = "2.9.1"
dash-bootstrap-templates = "1.0.8"
ipywidgets = "8.0.6"
jupyter-dash = "0.4.2"
kaleido = "0.2.1"
notebook = "6.5.4"
numba = "0.58.1"
numpy = "1.24.0"
pandas = "2.0.3"
ta-lib = "0.4.28"
plotly = "5.16.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"