[tool.poetry]
name = "quantfreedom"
version = "0.1.4.6"
description = "This is where the description goes but i am not going to put one because i am lazy ... thank you i love you!"
authors = ["QuantFreedom <QuantFreedom1022@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
ipykernel = "6.25.0"
dash = "2.9.1"
dash-bootstrap-templates = "1.1.1"
ipywidgets = "8.1.1"
jupyter-dash = "0.4.2"
notebook = "6.5.6"
numba = "0.58.1"
numpy = "1.26.1"
pandas = "2.1.1"
plotly = "5.17.0"
kaleido = [
{version="0.1.*", markers="sys_platform != 'darwin'", source = "pypi"},
{version="0.2.*", markers="sys_platform == 'darwin'", source = "pypi"},
]


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
mysql-connector-python = "8.3.0"
poetry = "1.7.1"
aws-cdk-lib = "2.133.0"
constructs = "10.0.0"
fastapi = "0.110.0"
mangum = "0.38.0"
httpx = "0.27.0"

[tool.poetry.group.aws]
optional = true

[tool.poetry.group.aws.dependencies]
numpy = "1.26.1"
fastapi = "0.110.0"
mangum = "0.38.0"
httpx = "0.27.0"
mysql-connector-python = "8.3.0"
cryptography = "42.0.5"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "1.5.3"
griffe = "0.38.0"
mkdocs-material = "9.4.14"
mkdocstrings = "0.24.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"